/** 100 English questions. Drawn at random without repeat until the deck is empty. */
export const QUESTIONS = [
  { type: "truth", prompt: "DUSD is StandX’s yield-bearing stablecoin and the margin / pricing asset.", truth: true },
  { type: "truth", prompt: "DUSD needs a separate staking lock before it can earn any yield.", truth: false },
  { type: "truth", prompt: "DUSD in the Perps Wallet can earn points and yield. DUSD in the Cash Wallet does not.", truth: true },
  { type: "truth", prompt: "StandX is a spot-only exchange with no perpetual markets.", truth: false },
  { type: "truth", prompt: "Maker Points can accrue on a limit order that never fills, if it rests long enough.", truth: true },
  { type: "truth", prompt: "A limit order cancelled in 0.1 seconds still instantly pays Maker Points.", truth: false },
  { type: "truth", prompt: "SIP-1 Block Trade lets large orders fill off the public book.", truth: true },
  { type: "truth", prompt: "SIP-1 is Universal Markets: anyone can open a ticker.", truth: false },
  { type: "truth", prompt: "SIP-2 Position Yield can send a share of protocol fees to open positions.", truth: true },
  { type: "truth", prompt: "SIP-3 says trading fees can grow DUSD native yield.", truth: true },
  { type: "truth", prompt: "SIP-4 Block Options can turn an exit intent into an option-like right on a position.", truth: true },
  { type: "truth", prompt: "SIP-5 Universal Markets lets anyone list a market.", truth: true },
  { type: "truth", prompt: "Under SIP-5, Shield Vault covers losses before ADL.", truth: true },
  { type: "truth", prompt: "Reward Vault is held to back maker liquidity.", truth: true },
  { type: "truth", prompt: "This Circuit screen is a vault explorer that shows Shield and Reward TVL.", truth: false },
  { type: "truth", prompt: "Pipe thickness on this map is 24h volume, not vault TVL.", truth: true },
  { type: "truth", prompt: "Node size on this map tracks open interest.", truth: true },
  { type: "truth", prompt: "The public depth x-ray also shows hidden block-trade inventory.", truth: false },
  { type: "truth", prompt: "Positive funding usually means longs pay shorts.", truth: true },
  { type: "truth", prompt: "StandX perps are priced and margined around DUSD.", truth: true },
  { type: "truth", prompt: "Community Maker Yield is for two-sided quotes near mark and for uptime.", truth: true },
  { type: "truth", prompt: "Holder points need DUSD in the Perps Wallet or a vault.", truth: true },
  { type: "truth", prompt: "ADL is last-resort socialized loss after insurance / shield layers.", truth: true },
  { type: "truth", prompt: "A maker rests on the book. A taker crosses the spread.", truth: true },
  { type: "truth", prompt: "Open interest is the same number as 24h volume.", truth: false },
  { type: "truth", prompt: "Mark price is the funding and liquidation reference, not only the last trade.", truth: true },
  { type: "truth", prompt: "Numbers on this app come from public market, depth, and kline feeds.", truth: true },
  { type: "truth", prompt: "SIP-5A Community Maker Yield is just a new name for SIP-1 Block Trade.", truth: false },
  { type: "truth", prompt: "Funding is a transfer between longs and shorts on a perp, not an equity dividend.", truth: true },
  { type: "truth", prompt: "Stander is the StandX mascot at the DUSD core of this circuit.", truth: true },
  { type: "truth", prompt: "A perpetual future has no fixed expiry.", truth: true },
  { type: "truth", prompt: "Liquidation closes a position when margin can no longer cover the move.", truth: true },
  { type: "truth", prompt: "Leverage increases both potential gain and potential loss.", truth: true },
  { type: "truth", prompt: "A bid is an offer to sell.", truth: false },
  { type: "truth", prompt: "An ask is an offer to sell.", truth: true },
  { type: "truth", prompt: "Spread is the gap between best bid and best ask.", truth: true },
  { type: "truth", prompt: "Notional is position size times price.", truth: true },
  { type: "truth", prompt: "Isolated margin shares one pool across every market you trade.", truth: false },
  { type: "truth", prompt: "Cross margin can share collateral across positions.", truth: true },
  { type: "truth", prompt: "A stop-loss is meant to cap downside if price runs against you.", truth: true },
  { type: "truth", prompt: "Funding rate is paid continuously between longs and shorts to pin the perp to spot.", truth: true },
  { type: "truth", prompt: "If funding is negative, shorts typically pay longs.", truth: true },
  { type: "truth", prompt: "Open interest falling while price rips always means a short squeeze finished.", truth: false },
  { type: "truth", prompt: "Depth is resting liquidity at nearby prices.", truth: true },
  { type: "truth", prompt: "Slippage is the extra cost when your order walks the book.", truth: true },
  { type: "truth", prompt: "A market order is guaranteed to rest as a maker.", truth: false },
  { type: "truth", prompt: "A post-only limit tries to add liquidity instead of taking it.", truth: true },
  { type: "truth", prompt: "Insurance / shield capital sits in front of ADL when the system can cover a loss.", truth: true },
  { type: "truth", prompt: "This site’s live tape is a substitute for StandX official docs.", truth: false },
  { type: "truth", prompt: "Nothing here is investment advice.", truth: true },
  { type: "truth", prompt: "DUSD is used as yield-bearing margin on StandX perps.", truth: true },
  { type: "truth", prompt: "Cash Wallet DUSD is the same yield engine as Perps Wallet DUSD.", truth: false },
  { type: "truth", prompt: "Block trades are designed to reduce market impact of large size.", truth: true },
  { type: "truth", prompt: "Universal Markets means only the team can list tickers.", truth: false },
  { type: "truth", prompt: "Position Yield is about routing fee share to open risk, not about listing tickers.", truth: true },
  { type: "truth", prompt: "Native DUSD yield can be fed by platform trading fees under SIP-3.", truth: true },
  { type: "truth", prompt: "Block Options invent a brand-new spot token for every exit.", truth: false },
  { type: "truth", prompt: "Shield Vault is meant to absorb losses before positions are ADL’d.", truth: true },
  { type: "truth", prompt: "Reward Vault is primarily an NFT marketplace.", truth: false },
  { type: "truth", prompt: "Maker quality includes being near mark and staying online.", truth: true },
  { type: "truth", prompt: "Taker fees are paid by the side that removes book liquidity.", truth: true },
  { type: "truth", prompt: "A wick on a candle is always a guaranteed fill you can trade at later.", truth: false },
  { type: "truth", prompt: "Mark and last price can differ; liquidations usually care about mark.", truth: true },
  { type: "truth", prompt: "OI is outstanding contracts, not the same as traded volume.", truth: true },
  { type: "truth", prompt: "A long profits if price falls, all else equal.", truth: false },
  { type: "truth", prompt: "A short profits if price falls, all else equal.", truth: true },
  { type: "truth", prompt: "This 3D ring is a live schematic, not a trading venue itself.", truth: true },
  { type: "truth", prompt: "Clicking TRADE ON STANDX leaves this schematic and goes to the real perps UI.", truth: true },
  { type: "truth", prompt: "Public APIs expose hidden block-trade blotters in full.", truth: false },
  { type: "truth", prompt: "Circuit pipes are a metaphor for 24h quote volume.", truth: true },
  { type: "sip", prompt: "Large orders can fill off the public book to cut market impact. Which SIP?", sip: "SIP-1" },
  { type: "sip", prompt: "Which SIP is named Block Trade?", sip: "SIP-1" },
  { type: "sip", prompt: "A share of protocol fees can go to qualifying open positions. Which SIP?", sip: "SIP-2" },
  { type: "sip", prompt: "Which SIP is Position Yield?", sip: "SIP-2" },
  { type: "sip", prompt: "Trading fees can grow DUSD native yield. Which SIP?", sip: "SIP-3" },
  { type: "sip", prompt: "Which SIP is DUSD Native Yield?", sip: "SIP-3" },
  { type: "sip", prompt: "An exit intent can become an option-like right on a live position. Which SIP?", sip: "SIP-4" },
  { type: "sip", prompt: "Which SIP is Block Options?", sip: "SIP-4" },
  { type: "sip", prompt: "Anyone can list a market; Reward and Shield vaults back the system. Which SIP?", sip: "SIP-5" },
  { type: "sip", prompt: "Which SIP is Universal Markets?", sip: "SIP-5" },
  { type: "sip", prompt: "Shield Vault covers losses before ADL. That design sits in which SIP?", sip: "SIP-5" },
  { type: "sip", prompt: "The public book x-ray does not show this flow: off-book large prints. Which SIP describes them?", sip: "SIP-1" },
  { type: "sip", prompt: "Fee share to open interest, not to new listings. Which SIP?", sip: "SIP-2" },
  { type: "sip", prompt: "Pipe thickness as fee activity feeding DUSD yield. Which SIP?", sip: "SIP-3" },
  { type: "sip", prompt: "Option-like exit rights, not a new spot listing. Which SIP?", sip: "SIP-4" },
  { type: "sip", prompt: "Permissionless market listing. Which SIP?", sip: "SIP-5" },
  { type: "sip", prompt: "Reward Vault backs makers. Which SIP package is that in?", sip: "SIP-5" },
  { type: "truth", prompt: "You should treat every Circuit number as a live but unofficial public snapshot.", truth: true },
  { type: "truth", prompt: "Vault TVL is plotted as node radius on this map.", truth: false },
  { type: "truth", prompt: "Stander at the center stands for the DUSD core, not a single listed perp.", truth: true },
  { type: "truth", prompt: "A limit order that rests can be a maker even if it later gets hit.", truth: true },
  { type: "truth", prompt: "ADL can assign leftover loss to opposing traders when the backstop is exhausted.", truth: true },
  { type: "truth", prompt: "Funding is a one-time IPO allocation.", truth: false },
  { type: "truth", prompt: "Perps let you express long or short without holding the spot asset.", truth: true },
  { type: "truth", prompt: "Higher open interest always means the market is safer.", truth: false },
  { type: "truth", prompt: "A thin book increases the chance of slippage.", truth: true },
  { type: "truth", prompt: "This game’s score is 10 points per correct answer.", truth: true },
  { type: "truth", prompt: "You get two lives in this raid.", truth: true },
  { type: "truth", prompt: "TRUE means the statement matches StandX / perp mechanics as framed here.", truth: true },
  { type: "truth", prompt: "FALSE means the statement is wrong or swapped with another SIP.", truth: true },
];
